<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWS.Lambda.Powertools.Logging" Version="3.2.2" />
        <PackageReference Include="AWS.Lambda.Powertools.Metrics" Version="3.2.2" />
        <PackageReference Include="AWS.Lambda.Powertools.Tracing" Version="3.2.2" />
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Plagiarism\Plagiarism.csproj" />
    </ItemGroup>

</Project>
